version: '3.9'

services:
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - mynetwork
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync

  backend:
    depends_on:
      - mongo
    build: ./backend
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DB_URL=${DB_URL}
      - PORT=${PORT}
    networks:
      - mynetwork
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync

  mongo:
    build: ./mongoDockerfile  # Use the custom Dockerfile
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_NOT_ROOT_PASSWORD=${MONGO_NOT_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - ./seed-data:/docker-entrypoint-initdb.d

    networks:
      - mynetwork
      
volumes:
  mongo-data:

networks:
  mynetwork:
    driver: bridge
    